package uitl;
import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PipedReader;
import java.io.PipedWriter;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import javax.swing.JFrame;
import org.apache.log4j.Appender;
import org.apache.log4j.Logger;
import org.apache.log4j.WriterAppender;
/*
 * NewJFrame.java
 *
 * Created on 2016-4-7, 16:39:37
 */

/**
 *
 * @author nantu
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener,  
WindowListener {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	int i=0;
    private MenuItem open, close;  
    threadupdate tu=new threadupdate();
    private static Logger logger = Logger.getLogger(NewJFrame.class);
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//设置日期格式
    public int getI() {
		return i;
	}

	public void setI(int i) {
		this.i = i;
	}

	/** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        addWindowListener(this); 
    }
    public void openFrame() {  
        setVisible(true);// 设置为可见  
       // setAlwaysOnTop(true);// 设置置顶  
        // 设置窗口状态(在最小化状态弹出显示)  
        setExtendedState(JFrame.NORMAL);  
    }  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        信息提示 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        同步日志 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        信息提示2 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        线程信息 = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        设置面板 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sqlip = new javax.swing.JTextField();
        sqlname = new javax.swing.JTextField();
        dbname = new javax.swing.JTextField();
        sqlid = new javax.swing.JTextField();
        sqlpw = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Extid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        party = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        domain = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        alias = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        saveprop = new javax.swing.JButton();
        closeprop = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        startupdatenow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        startupdate = new javax.swing.JButton();
        stopupdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        设置按钮 = new javax.swing.JMenu();

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("后台数据同步线程已经启动");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("信息提示");

        jButton4.setText("关闭");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout 信息提示Layout = new javax.swing.GroupLayout(信息提示.getContentPane());
        信息提示.getContentPane().setLayout(信息提示Layout);
        信息提示Layout.setHorizontalGroup(
            信息提示Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(信息提示Layout.createSequentialGroup()
                .addGroup(信息提示Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(信息提示Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3))
                    .addGroup(信息提示Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(信息提示Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton4)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        信息提示Layout.setVerticalGroup(
            信息提示Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(信息提示Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setText("同步日志");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout 同步日志Layout = new javax.swing.GroupLayout(同步日志.getContentPane());
        同步日志.getContentPane().setLayout(同步日志Layout);
        同步日志Layout.setHorizontalGroup(
            同步日志Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(同步日志Layout.createSequentialGroup()
                .addGroup(同步日志Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(同步日志Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel4))
                    .addGroup(同步日志Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        同步日志Layout.setVerticalGroup(
            同步日志Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(同步日志Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel5.setText("开始执行数据同步");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("信息提示");

        jButton6.setText("关闭");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout 信息提示2Layout = new javax.swing.GroupLayout(信息提示2.getContentPane());
        信息提示2.getContentPane().setLayout(信息提示2Layout);
        信息提示2Layout.setHorizontalGroup(
            信息提示2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(信息提示2Layout.createSequentialGroup()
                .addGroup(信息提示2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(信息提示2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel6))
                    .addGroup(信息提示2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton6))
                    .addGroup(信息提示2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel5))
                    .addGroup(信息提示2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(信息提示2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        信息提示2Layout.setVerticalGroup(
            信息提示2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(信息提示2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(19, 19, 19))
        );

        jLabel7.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel7.setText("线程信息");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout 线程信息Layout = new javax.swing.GroupLayout(线程信息.getContentPane());
        线程信息.getContentPane().setLayout(线程信息Layout);
        线程信息Layout.setHorizontalGroup(
            线程信息Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(线程信息Layout.createSequentialGroup()
                .addGroup(线程信息Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(线程信息Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel7))
                    .addGroup(线程信息Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        线程信息Layout.setVerticalGroup(
            线程信息Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(线程信息Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel8.setText("设置");

        jLabel9.setText("数据库ip");

        jLabel10.setText("用户名称");

        jLabel11.setText("表名称");

        jLabel12.setText("端口号");

        jLabel13.setText("用户密码");

        jLabel14.setText("数据库id");

        sqlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlipActionPerformed(evt);
            }
        });

        sqlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlnameActionPerformed(evt);
            }
        });

        dbname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbnameActionPerformed(evt);
            }
        });

        sqlid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlidActionPerformed(evt);
            }
        });

        sqlpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlpwActionPerformed(evt);
            }
        });

        port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portActionPerformed(evt);
            }
        });

        jLabel16.setText("姓名字段");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel17.setText("性别字段");

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        jLabel18.setText("工号字段");

        Extid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtidActionPerformed(evt);
            }
        });

        jLabel19.setText("部门字段");

        party.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyActionPerformed(evt);
            }
        });

        jLabel23.setText("手机字段");

        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });

        jLabel24.setText("域名");

        domain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainActionPerformed(evt);
            }
        });

        jLabel25.setText("CorpId");

        alias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliasActionPerformed(evt);
            }
        });

        jLabel26.setText("Sercet");

        key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyActionPerformed(evt);
            }
        });

        saveprop.setText("保存");
        saveprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepropActionPerformed(evt);
            }
        });

        closeprop.setText("关闭");
        closeprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closepropActionPerformed(evt);
            }
        });

        jLabel27.setText("状态字段");

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jLabel28.setText("密码字段");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout 设置面板Layout = new javax.swing.GroupLayout(设置面板.getContentPane());
        设置面板.getContentPane().setLayout(设置面板Layout);
        设置面板Layout.setHorizontalGroup(
            设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(设置面板Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(设置面板Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(设置面板Layout.createSequentialGroup()
                        .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sqlip, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(sqlname)
                                    .addComponent(dbname, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Extid)
                                    .addComponent(username)
                                    .addComponent(mobile)
                                    .addComponent(password))))
                        .addGap(47, 47, 47)
                        .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(party))
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gender))
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alias))
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(设置面板Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(port, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                    .addGroup(设置面板Layout.createSequentialGroup()
                                        .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sqlpw)
                                            .addComponent(sqlid, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(设置面板Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status)))))
                .addContainerGap(49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(设置面板Layout.createSequentialGroup()
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(设置面板Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel8))
                    .addGroup(设置面板Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(saveprop, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(closeprop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        设置面板Layout.setVerticalGroup(
            设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(设置面板Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sqlid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(sqlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sqlpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(dbname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Extid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(party, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(设置面板Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveprop)
                    .addComponent(closeprop))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(546, 328));

        startupdatenow.setText("启动即时同步");
        startupdatenow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startupdatenowActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("楷体", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("宿迁学院企业邮箱数据同步");

        startupdate.setText("启动后台同步");
        startupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					startupdateActionPerformed(evt);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        stopupdate.setText("中断数据同步");
        stopupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopupdateActionPerformed(evt);
            }
        });

        jButton3.setText("查看同步日志");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("查看线程信息");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setText("查看故障日志");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startupdatenow, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(stopupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(startupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startupdatenow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 546, 328);

        jPanel2.setMinimumSize(new java.awt.Dimension(560, 282));
        jPanel2.setPreferredSize(new java.awt.Dimension(546, 328));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uitl/1.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setPreferredSize(new java.awt.Dimension(560, 310));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(0, 0, 546, 328);

        设置按钮.setText("设置");
        设置按钮.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					设置按钮MouseClicked(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        设置按钮.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                设置按钮ActionPerformed(evt);
            }
        });
        jMenuBar1.add(设置按钮);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startupdateActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {//GEN-FIRST:event_startupdateActionPerformed
        // TODO add your handling code here:
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        线程信息.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
        线程信息.setVisible(true);
        线程信息.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Logger root = Logger.getLogger("Log4jMain");
        try{
           // 获取子记录器的输出源
           Appender appender = root.getAppender("WriterAppender");
           // 定义一个未连接的输入流管道
           PipedReader reader = new PipedReader();
           // 定义一个已连接的输出流管理，并连接到reader
           Writer writer = new PipedWriter( reader) ;
           // 设置 appender 输出流
           ((WriterAppender) appender).setWriter(writer);
          
           Thread t = new AppenderThread(reader);
           t.start();

        }catch(Exception e){
               logger.error(e);
           }
         信息提示.setBounds((screenSize.width-300)/2, (screenSize.height-170)/2, 300, 170);
         信息提示.setResizable(false);
        信息提示.setVisible(true);
        threadupdate tu=new threadupdate();
        try {
			tu.start();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_startupdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

  	if(threadupdate.update.isAlive()){
  		jTextArea1.setText("");

          List<String> log=readlog.readTxtFile("c:\\logs\\log.log",jTextArea1);

         
          java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
          同步日志.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
          同步日志.setVisible(true);
          同步日志.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
          log.clear();
  	}else{
  		List<String> log=readlog.readTxtFile("c:\\logs\\log.log",jTextArea1);
          java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
          同步日志.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
          同步日志.setVisible(true);
          同步日志.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
          log.clear();
       }
  }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        信息提示.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    	if(threadupdate.update.isAlive()){
    		jTextArea1.setText("");
            List<String> err=readlog.readTxtFile("c:\\logs\\error.log",jTextArea1);
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            同步日志.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
            同步日志.setVisible(true);
            同步日志.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            err.clear();
    	}else{
    		List<String> err=readlog.readTxtFile("c:\\logs\\error.log",jTextArea1);
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            同步日志.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
            同步日志.setVisible(true);
            同步日志.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            err.clear();
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void startupdatenowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startupdatenowActionPerformed
            // TODO add your handling code here:
        if(i==1){
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
         信息提示2.setBounds((screenSize.width - 400) / 2, (screenSize.height - 300) / 2, 400, 300);
            信息提示2.setResizable(false);
            信息提示2.setVisible(true);
        }else{
            try {
                i = 1;
                jProgressBar1.setStringPainted(true);
                java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                信息提示2.setBounds((screenSize.width - 400) / 2, (screenSize.height - 300) / 2, 400, 300);
                信息提示2.setResizable(false);
                信息提示2.setVisible(true);
                if(threadupdate.update.isAlive()){
                threadupdate newtu=new threadupdate();
                newtu.update(jTextArea3, jProgressBar1);}else{
                	tu.update(jTextArea3, jProgressBar1);
                }
            } catch (InterruptedException ex) {
                java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_startupdatenowActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        信息提示2.dispose();
        jTextArea3.setText("");
        jProgressBar1.setValue(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        线程信息.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
        线程信息.setVisible(true);
        线程信息.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       Logger root = Logger.getLogger("Log4jMain");
         try{
            // 获取子记录器的输出源
            Appender appender = root.getAppender("WriterAppender");
            // 定义一个未连接的输入流管道
            PipedReader reader = new PipedReader();
            // 定义一个已连接的输出流管理，并连接到reader
            Writer writer = new PipedWriter( reader) ;
            // 设置 appender 输出流
            ((WriterAppender) appender).setWriter(writer);
            Thread t = new AppenderThread(reader);
            t.start();
         }catch(Exception e){
                logger.error(e);
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void stopupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopupdateActionPerformed
        try {
            // TODO add your handling code here:
        	java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            线程信息.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2, 500, 300);
            线程信息.setVisible(true);
            线程信息.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jTextArea2.append("正在中断线程。。。"+"\n");
            tu.stop(jTextArea2);
        } catch (InterruptedException ex) {
        	logger.info("线程已经中断。");
        }

    }//GEN-LAST:event_stopupdateActionPerformed

    private void sqlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlipActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_sqlipActionPerformed

    private void sqlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlnameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_sqlnameActionPerformed

    private void dbnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbnameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dbnameActionPerformed

    private void sqlidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlidActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_sqlidActionPerformed

    private void sqlpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlpwActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_sqlpwActionPerformed

    private void portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_portActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_usernameActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_genderActionPerformed

    private void ExtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtidActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ExtidActionPerformed

    private void partyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partyActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_partyActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mobileActionPerformed

    private void 设置按钮ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_设置按钮ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_设置按钮ActionPerformed

    private void 设置按钮MouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_设置按钮MouseClicked
        // TODO add your handling code here:
    	 Properties prop = new Properties();
    	 InputStream ip = new FileInputStream("c:\\sql.properties" );
    	    prop.load(ip);
    	    sqlip.setText(prop.getProperty("sqlip"));
    	    sqlid.setText(prop.getProperty("sqlname"));
    	    sqlname.setText(prop.getProperty("username"));
    	    sqlpw.setText(prop.getProperty("userpassword"));
    	    username.setText(prop.getProperty("namezd"));
    	    port.setText(prop.getProperty("port"));
    	    key.setText(prop.getProperty("key"));
    	    Extid.setText(prop.getProperty("ExtIdzd"));
    	    alias.setText(prop.getProperty("alias"));
    	    dbname.setText(prop.getProperty("dbname"));
    	    domain.setText(prop.getProperty("domain"));
    	    gender.setText(prop.getProperty("Genderzd"));
    	    party.setText(prop.getProperty("partyzd"));
            mobile.setText(prop.getProperty("mobilezd"));
            password.setText(prop.getProperty("passwordzd"));
            status.setText(prop.getProperty("statuszd"));
    	    ip.close();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            设置面板.setBounds((screenSize.width-500)/2, (screenSize.height-330)/2, 560, 480);
            设置面板.setVisible(true);
            设置面板.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_设置按钮MouseClicked

    private void domainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_domainActionPerformed

    private void aliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aliasActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_aliasActionPerformed

    private void keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_keyActionPerformed

    private void savepropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepropActionPerformed
        FileOutputStream fos = null;
        try {
            String sqlipt = sqlip.getText();
            String sqlidt = sqlid.getText();
            String sqlnamet = sqlname.getText();
            String sqlpwt = sqlpw.getText();
            String usernamet = username.getText();
            String portt = port.getText();
            String keyt = key.getText();
            String Extidt = Extid.getText();
            String aliast = alias.getText();
            String dbnamet = dbname.getText();
            String domaint = domain.getText();
            String gendert = gender.getText();
            String mobilet=mobile.getText();
            String partyt = party.getText();
            String statust = status.getText();
            String passwordt = password.getText();
            Properties prop = new Properties();
            fos = new FileOutputStream("c:\\sql.properties");
            prop.setProperty("port", portt);
            prop.setProperty("ExtIdzd",Extidt);
            prop.setProperty("sqlip", sqlipt);
            prop.setProperty("username", sqlnamet);
            prop.setProperty("sqlname", sqlidt);
            prop.setProperty("userpassword", sqlpwt);
            prop.setProperty("domain", domaint);
            prop.setProperty("alias", aliast);
            prop.setProperty("Genderzd", gendert);
            prop.setProperty("key", keyt);
            prop.setProperty("dbname", dbnamet);
            prop.setProperty("namezd", usernamet);
            prop.setProperty("mobilezd", mobilet);
            prop.setProperty("partyzd", partyt);
            prop.setProperty("statuszd", statust);
            prop.setProperty("passwordzd", passwordt);
            //保存，并加入注释
            prop.store(fos, "Update 'port' value");
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } finally {
            try {
                fos.close();
                设置面板.dispose();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_savepropActionPerformed

    private void closepropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closepropActionPerformed
        // TODO add your handling code here:
        设置面板.dispose();
    }//GEN-LAST:event_closepropActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
   class AppenderThread extends Thread {
    PipedReader reader;

    public AppenderThread(PipedReader reader) {
        this.reader = reader;
    }
    public void run() {
        // 不间断地扫描输入流
        @SuppressWarnings("resource")
		Scanner scanner = new Scanner(reader);
        while (scanner.hasNext()) {
        	String datetime=df.format(new Date());// new Date()为获取当前系统时间
        	String[] dt=datetime.split(" ");
        	String time=dt[1];
        	if(time.equals("06:00:00")||time.equals("12:00:00")||time.equals("18:00:00")||time.equals("24:00:00")){
        		scanner.close();
        		scanner= new Scanner(reader);
        	}
             jTextArea2.append(scanner.nextLine()+"\n");
        }
    }
}
   
    class NewAppenderThread extends Thread {
    PipedReader reader;

    public NewAppenderThread(PipedReader reader) {
        this.reader = reader;
    }

    public void run() {
        // 不间断地扫描输入流
        @SuppressWarnings("resource")
		Scanner scanner = new Scanner(reader);
        while (scanner.hasNext()) {
             jTextArea3.append(scanner.nextLine()+"\n");

        }
    }
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            	NewJFrame njf=new NewJFrame();
                 njf.setVisible(true);
                 njf.setResizable(false);
                 njf.setBounds((screenSize.width-500)/2, (screenSize.height-300)/2,540,330);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Extid;
    private javax.swing.JTextField alias;
    private javax.swing.JButton closeprop;
    private javax.swing.JTextField dbname;
    private javax.swing.JTextField domain;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField key;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField party;
    private javax.swing.JTextField password;
    private javax.swing.JTextField port;
    private javax.swing.JButton saveprop;
    private javax.swing.JTextField sqlid;
    private javax.swing.JTextField sqlip;
    private javax.swing.JTextField sqlname;
    private javax.swing.JTextField sqlpw;
    private javax.swing.JButton startupdate;
    private javax.swing.JButton startupdatenow;
    private javax.swing.JTextField status;
    private javax.swing.JButton stopupdate;
    private javax.swing.JTextField username;
    private javax.swing.JDialog 信息提示;
    private javax.swing.JDialog 信息提示2;
    private javax.swing.JFrame 同步日志;
    private javax.swing.JFrame 线程信息;
    private javax.swing.JMenu 设置按钮;
    private javax.swing.JFrame 设置面板;
    // End of variables declaration//GEN-END:variables

	@Override
	public void windowActivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowClosed(WindowEvent arg0) {
		// TODO Auto-generated method stub
		dispose();  
	}

	@Override
	public void windowClosing(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowDeactivated(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowDeiconified(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void windowIconified(WindowEvent arg0) {  
        setVisible(false);// 设置为不可见  
    }

	@Override
	public void windowOpened(WindowEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		 if (e.getSource() == open) {  
	            openFrame();  
	        }  
	        if (e.getSource() == close) {  
	            System.exit(-1);  
	        }
	}

}
